### ISSUE TITLE
Couldn't read item tag list fruitful:gives_sustaining_long from fruitful:tags/items/gives_sustaining_long.json

### ISSUE THREAD

**Issue by curryducker** [teamauroramods/Fruitful#2]
I saw this error while i was starting a server with the Fruitful mod, the apple pie from environmental that's in that json file doesn't receive the tag.
![image](https://user-images.githubusercontent.com/66020230/178138224-d3c48ab6-cb41-411e-9401-a14330ceb349.png)
Not a big issue but still something i wanted to report :)

**Comment by ebo2022** [comment]
The issue seems to be caused because the tag format may be outdated, this will probably be fixed in the pollen release
